default_velocity_scaling_factor: 1.0
default_acceleration_scaling_factor: 1.0

joint_limits:
  J1:
    has_position_limits: true
    min_position: -1.083 # -62.047 degrees in radians
    max_position: 2.148   # 123.047 degrees in radians
    has_velocity_limits: true
    max_velocity: 4.6  # 0.92 rad/s * 2.0
    has_acceleration_limits: false
    max_acceleration: 0.81  # 0.54 rad/s² * 1.5
    
    
  J2:
    has_position_limits: true
    min_position: -1.221  # -55 degrees in radians
    max_position: 0.907   # 49 degrees in radians
    has_velocity_limits: true
    max_velocity: 1.75  # 0.35 rad/s * 2.0
    has_acceleration_limits: false
    max_acceleration: 0.36  # 0.24 rad/s² * 1.5
    
    
  J3:
    has_position_limits: true
    min_position: -1.8825  # -72.13 degrees in radians
    max_position: 1.2566   # 57 degrees in radians
    has_velocity_limits: true
    max_velocity: 1.75  # 0.35 rad/s * 2.0
    has_acceleration_limits: false
    max_acceleration: 0.375  # 0.25 rad/s² * 1.5
    
    
  J4:
    has_position_limits: true
    min_position: -1.841  # -105.47 degrees in radians
    max_position: 1.841   # 105.47 degrees in radians
    has_velocity_limits: true
    max_velocity: 4.9  # 0.98 rad/s * 2.0
    has_acceleration_limits: false
    max_acceleration: 0.915  # 0.61 rad/s² * 1.5
    
    
  J5:
    has_position_limits: true
    min_position: -1.571  # -90 degrees in radians
    max_position: 1.571   # 90 degrees in radians
    has_velocity_limits: true
    max_velocity: 4.9  # 0.98 rad/s * 2.0
    has_acceleration_limits: false
    max_acceleration: 0.915  # 0.61 rad/s² * 1.5
    
    
  J6:
    has_position_limits: true
    min_position: -3.142  # -180 degrees in radians
    max_position: 3.142   # 180 degrees in radians
    has_velocity_limits: true
    max_velocity: 4.35  # 0.87 rad/s * 2.0
    has_acceleration_limits: false
    max_acceleration: 0.735  # 0.49 rad/s² * 1.5
    
    